// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `JsonAuto`, `___JsonAutoReconcileKeyType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `fmt`, `from`, `from`, `hydrate_key`, `hydrate_map`, `hydrate_string`, `key`, `reconcile`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DocHandle>>
abstract class DocHandle implements RustOpaqueInterface {
  Future<DocHandle> fork();

  Future<String> hydrateJson();

  static Future<DocHandle> load({required List<int> bytes}) =>
      RustLib.instance.api.crateApiDocDocHandleLoad(bytes: bytes);

  Future<void> merge({required DocHandle other});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DocHandle> newInstance() =>
      RustLib.instance.api.crateApiDocDocHandleNew();

  Future<void> reconcileJson({required String jsonStr});

  Future<Uint8List> save();
}
