// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'doc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List?> generateSyncMessage({
  required DocHandle doc,
  required SyncStateHandle syncState,
}) => RustLib.instance.api.crateApiSyncGenerateSyncMessage(
  doc: doc,
  syncState: syncState,
);

Future<void> receiveSyncMessage({
  required DocHandle doc,
  required SyncStateHandle syncState,
  required List<int> message,
}) => RustLib.instance.api.crateApiSyncReceiveSyncMessage(
  doc: doc,
  syncState: syncState,
  message: message,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncStateHandle>>
abstract class SyncStateHandle implements RustOpaqueInterface {
  static Future<SyncStateHandle> create() =>
      RustLib.instance.api.crateApiSyncSyncStateHandleCreate();

  static Future<void> decodeMessage({required List<int> message}) => RustLib
      .instance
      .api
      .crateApiSyncSyncStateHandleDecodeMessage(message: message);
}
